// SHA-256 of the proving assets the browser downloads (frontend/public/zk/*): T18 of the threat model.
//   node scripts/zk-hashes.js write   -> frontend/src/lib/zk-hashes.ts (commit it; regenerate after every ceremony/rebuild)
//   node scripts/zk-hashes.js check   -> exits 1 when an asset no longer matches the committed hashes
// The browser verifies each downloaded asset against these hashes before proving (frontend/src/lib/zk.ts), and the same
// hashes are published in docs/audit so anyone can compare them with what the site serves.
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");
const ROOT = path.join(__dirname, "..");
const DIR = path.join(ROOT, "frontend", "public", "zk");
const OUT = path.join(ROOT, "frontend", "src", "lib", "zk-hashes.ts");
const FILES = ["withdraw.wasm", "withdraw_final.zkey", "ragequit.wasm", "ragequit_final.zkey"];

const current = () => Object.fromEntries(FILES.map((f) => [f, crypto.createHash("sha256").update(fs.readFileSync(path.join(DIR, f))).digest("hex")]));

if (require.main === module) {
  const mode = process.argv[2] || "check";
  const now = current();
  if (mode === "write") {
    fs.writeFileSync(OUT, "// Generated by scripts/zk-hashes.js: SHA-256 of frontend/public/zk/*. Do not edit by hand.\nexport const ZK_HASHES: Record<string, string> = " + JSON.stringify(now, null, 2) + ";\n");
    console.log("written", OUT);
    for (const [f, h] of Object.entries(now)) console.log(h, f);
  } else {
    const saved = JSON.parse(fs.readFileSync(OUT, "utf8").replace(/^[\s\S]*?= /, "").replace(/;\s*$/, ""));
    const bad = FILES.filter((f) => saved[f] !== now[f]);
    if (bad.length) { console.error("MISMATCH:", bad.join(", ")); process.exit(1); }
    console.log("zk asset hashes match");
  }
}
module.exports = { current, FILES };
