// Generated by scripts/zk-hashes.js: SHA-256 of frontend/public/zk/*. Do not edit by hand.
export const ZK_HASHES: Record<string, string> = {
  "withdraw.wasm": "839d5a51eda2e0855712e6d3594adb55a73ab048b680f034cce3145d74730092",
  "withdraw_final.zkey": "d912b91c014b7f6ace87e5ee0fcff24029b16d9a5675fe4be5d51a2b5b33d400",
  "ragequit.wasm": "3d99dd0c0bffecea5acd8f39e56217be87b936012b4ad0b8dd5ac2b5f60680de",
  "ragequit_final.zkey": "c334e49f69128480c0b1d5a9595abe4019134496890065b5974edbf106bbf4fd"
};
